# Generated by Django 6.0.4 on 2026-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(choices=[('POLICE', 'Police Department'), ('MEDICAL', 'Medical Unit'), ('FIRE', 'Fire Rescue')], max_length=20)),
            ],
        ),
    ]
