# Generated by Django 6.0.4 on 2026-04-14 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_officialresponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.venue'),
        ),
    ]
