# Generated by Django 6.0.4 on 2026-04-14 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emergencyalert_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.venue'),
        ),
        migrations.AddField(
            model_name='officialresponder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
